services:
  postgres:
    container_name: nexone-pci-postgres
    ports:
      - "5440:5432"

  backend:
    container_name: nexone-pci-backend
    ports:
      - "8091:8080"

  frontend:
    container_name: nexone-pci-frontend
    ports:
      - "3010:80"
